// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/sibtaina/provider-cloudflare/apis/access/v1alpha1"
	v1alpha1account "github.com/sibtaina/provider-cloudflare/apis/account/v1alpha1"
	v1alpha1api "github.com/sibtaina/provider-cloudflare/apis/api/v1alpha1"
	v1alpha1argo "github.com/sibtaina/provider-cloudflare/apis/argo/v1alpha1"
	v1alpha1authenticated "github.com/sibtaina/provider-cloudflare/apis/authenticated/v1alpha1"
	v1alpha1bot "github.com/sibtaina/provider-cloudflare/apis/bot/v1alpha1"
	v1alpha1byo "github.com/sibtaina/provider-cloudflare/apis/byo/v1alpha1"
	v1alpha1calls "github.com/sibtaina/provider-cloudflare/apis/calls/v1alpha1"
	v1alpha1certificate "github.com/sibtaina/provider-cloudflare/apis/certificate/v1alpha1"
	v1alpha1cloud "github.com/sibtaina/provider-cloudflare/apis/cloud/v1alpha1"
	v1alpha1cloudflare "github.com/sibtaina/provider-cloudflare/apis/cloudflare/v1alpha1"
	v1alpha1cloudforce "github.com/sibtaina/provider-cloudflare/apis/cloudforce/v1alpha1"
	v1alpha1content "github.com/sibtaina/provider-cloudflare/apis/content/v1alpha1"
	v1alpha1custom "github.com/sibtaina/provider-cloudflare/apis/custom/v1alpha1"
	v1alpha1d1 "github.com/sibtaina/provider-cloudflare/apis/d1/v1alpha1"
	v1alpha1dns "github.com/sibtaina/provider-cloudflare/apis/dns/v1alpha1"
	v1alpha1email "github.com/sibtaina/provider-cloudflare/apis/email/v1alpha1"
	v1alpha1firewall "github.com/sibtaina/provider-cloudflare/apis/firewall/v1alpha1"
	v1alpha1hostname "github.com/sibtaina/provider-cloudflare/apis/hostname/v1alpha1"
	v1alpha1hyperdrive "github.com/sibtaina/provider-cloudflare/apis/hyperdrive/v1alpha1"
	v1alpha1image "github.com/sibtaina/provider-cloudflare/apis/image/v1alpha1"
	v1alpha1keyless "github.com/sibtaina/provider-cloudflare/apis/keyless/v1alpha1"
	v1alpha1leaked "github.com/sibtaina/provider-cloudflare/apis/leaked/v1alpha1"
	v1alpha1list "github.com/sibtaina/provider-cloudflare/apis/list/v1alpha1"
	v1alpha1load "github.com/sibtaina/provider-cloudflare/apis/load/v1alpha1"
	v1alpha1logpull "github.com/sibtaina/provider-cloudflare/apis/logpull/v1alpha1"
	v1alpha1logpush "github.com/sibtaina/provider-cloudflare/apis/logpush/v1alpha1"
	v1alpha1magic "github.com/sibtaina/provider-cloudflare/apis/magic/v1alpha1"
	v1alpha1managed "github.com/sibtaina/provider-cloudflare/apis/managed/v1alpha1"
	v1alpha1mtls "github.com/sibtaina/provider-cloudflare/apis/mtls/v1alpha1"
	v1alpha1notification "github.com/sibtaina/provider-cloudflare/apis/notification/v1alpha1"
	v1alpha1observatory "github.com/sibtaina/provider-cloudflare/apis/observatory/v1alpha1"
	v1alpha1origin "github.com/sibtaina/provider-cloudflare/apis/origin/v1alpha1"
	v1alpha1page "github.com/sibtaina/provider-cloudflare/apis/page/v1alpha1"
	v1alpha1pages "github.com/sibtaina/provider-cloudflare/apis/pages/v1alpha1"
	v1alpha1queue "github.com/sibtaina/provider-cloudflare/apis/queue/v1alpha1"
	v1alpha1r2 "github.com/sibtaina/provider-cloudflare/apis/r2/v1alpha1"
	v1alpha1rate "github.com/sibtaina/provider-cloudflare/apis/rate/v1alpha1"
	v1alpha1regional "github.com/sibtaina/provider-cloudflare/apis/regional/v1alpha1"
	v1alpha1registrar "github.com/sibtaina/provider-cloudflare/apis/registrar/v1alpha1"
	v1alpha1snippet "github.com/sibtaina/provider-cloudflare/apis/snippet/v1alpha1"
	v1alpha1spectrum "github.com/sibtaina/provider-cloudflare/apis/spectrum/v1alpha1"
	v1alpha1stream "github.com/sibtaina/provider-cloudflare/apis/stream/v1alpha1"
	v1alpha1tiered "github.com/sibtaina/provider-cloudflare/apis/tiered/v1alpha1"
	v1alpha1total "github.com/sibtaina/provider-cloudflare/apis/total/v1alpha1"
	v1alpha1turnstile "github.com/sibtaina/provider-cloudflare/apis/turnstile/v1alpha1"
	v1alpha1url "github.com/sibtaina/provider-cloudflare/apis/url/v1alpha1"
	v1alpha1user "github.com/sibtaina/provider-cloudflare/apis/user/v1alpha1"
	v1alpha1apis "github.com/sibtaina/provider-cloudflare/apis/v1alpha1"
	v1beta1 "github.com/sibtaina/provider-cloudflare/apis/v1beta1"
	v1alpha1waiting "github.com/sibtaina/provider-cloudflare/apis/waiting/v1alpha1"
	v1alpha1web "github.com/sibtaina/provider-cloudflare/apis/web/v1alpha1"
	v1alpha1web3 "github.com/sibtaina/provider-cloudflare/apis/web3/v1alpha1"
	v1alpha1workers "github.com/sibtaina/provider-cloudflare/apis/workers/v1alpha1"
	v1alpha1zero "github.com/sibtaina/provider-cloudflare/apis/zero/v1alpha1"
	v1alpha1zone "github.com/sibtaina/provider-cloudflare/apis/zone/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1account.SchemeBuilder.AddToScheme,
		v1alpha1api.SchemeBuilder.AddToScheme,
		v1alpha1argo.SchemeBuilder.AddToScheme,
		v1alpha1authenticated.SchemeBuilder.AddToScheme,
		v1alpha1bot.SchemeBuilder.AddToScheme,
		v1alpha1byo.SchemeBuilder.AddToScheme,
		v1alpha1calls.SchemeBuilder.AddToScheme,
		v1alpha1certificate.SchemeBuilder.AddToScheme,
		v1alpha1cloud.SchemeBuilder.AddToScheme,
		v1alpha1cloudflare.SchemeBuilder.AddToScheme,
		v1alpha1cloudforce.SchemeBuilder.AddToScheme,
		v1alpha1content.SchemeBuilder.AddToScheme,
		v1alpha1custom.SchemeBuilder.AddToScheme,
		v1alpha1d1.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1email.SchemeBuilder.AddToScheme,
		v1alpha1firewall.SchemeBuilder.AddToScheme,
		v1alpha1hostname.SchemeBuilder.AddToScheme,
		v1alpha1hyperdrive.SchemeBuilder.AddToScheme,
		v1alpha1image.SchemeBuilder.AddToScheme,
		v1alpha1keyless.SchemeBuilder.AddToScheme,
		v1alpha1leaked.SchemeBuilder.AddToScheme,
		v1alpha1list.SchemeBuilder.AddToScheme,
		v1alpha1load.SchemeBuilder.AddToScheme,
		v1alpha1logpull.SchemeBuilder.AddToScheme,
		v1alpha1logpush.SchemeBuilder.AddToScheme,
		v1alpha1magic.SchemeBuilder.AddToScheme,
		v1alpha1managed.SchemeBuilder.AddToScheme,
		v1alpha1mtls.SchemeBuilder.AddToScheme,
		v1alpha1notification.SchemeBuilder.AddToScheme,
		v1alpha1observatory.SchemeBuilder.AddToScheme,
		v1alpha1origin.SchemeBuilder.AddToScheme,
		v1alpha1page.SchemeBuilder.AddToScheme,
		v1alpha1pages.SchemeBuilder.AddToScheme,
		v1alpha1queue.SchemeBuilder.AddToScheme,
		v1alpha1r2.SchemeBuilder.AddToScheme,
		v1alpha1rate.SchemeBuilder.AddToScheme,
		v1alpha1regional.SchemeBuilder.AddToScheme,
		v1alpha1registrar.SchemeBuilder.AddToScheme,
		v1alpha1snippet.SchemeBuilder.AddToScheme,
		v1alpha1spectrum.SchemeBuilder.AddToScheme,
		v1alpha1stream.SchemeBuilder.AddToScheme,
		v1alpha1tiered.SchemeBuilder.AddToScheme,
		v1alpha1total.SchemeBuilder.AddToScheme,
		v1alpha1turnstile.SchemeBuilder.AddToScheme,
		v1alpha1url.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1waiting.SchemeBuilder.AddToScheme,
		v1alpha1web.SchemeBuilder.AddToScheme,
		v1alpha1web3.SchemeBuilder.AddToScheme,
		v1alpha1workers.SchemeBuilder.AddToScheme,
		v1alpha1zero.SchemeBuilder.AddToScheme,
		v1alpha1zone.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
